export const ERC721_CONTRACT_ADDRESS = "YOUR ERC721_CONTRACT_ADDRESS";   
export const ERC20_CONTRACT_ADDRESS = "YOUR ERC20_CONTRACT_ADDRESS";   
export const ERC1155_CONTRACT_ADDRESS = "YOUR ERC1155_CONTRACT_ADDRESS";   

export const TIP_JAR_CONTRACT_ADDRESS = "YOUR TIP_JAR_CONTRACT_ADDRESS";
export const STAKING_CONTRACT_ADDRESS = "YOUR STAKING_CONTRACT_ADDRESS";
export const PROFILE_STATUS_CONTRACT_ADDRESS = "YOUR PROFILE_STATUS_CONTRACT_ADDRESS";
